license_id: "cc-by-igo"
methodology: Other
methodology_other: |
  Raster

  - Daily FloodScan SFED(flood fraction) band obtained directly from AER.

  - Daily historical SFED  band smoothed with 11 day centered rolling mean (+/-5 days).

  - Average day-of-year (DOY) raster calculated using last  10 years of smoothed data (2013-2023) to create SFED Baseline band.

  - SFED & SFED Baseline band merged per day.

  - Last 90 days of merged SFED + SFED Baseline bands zipped.

  Tabular

  - Daily zonal stats (mean) for all historical SFED data 1998-01-01 - 2023-12-31 for each Admin 2 covered by FloodScan extent.

  - Return periods calculated form zonal mean data per admin 2 using the Log III Pearson distribution.
caveats: "Modified and Simplified by UN OCHA"
dataset_source: "AER FloodScan: Atmospheric and Environmental Research (AER)."
package_creator: "isabelle-tot"
private: False
maintainer: "2f9fd160-2a16-49c0-89d6-0bc3230599bf"
owner_org: "aer"
data_update_frequency: 7
subnational: 0
