# Collector specific configuration
#TODO add details below to github secrets
url: "test"
account: "account"
container: "container"
last90_days_filename: "{dir}baseline_v2024-01-31_v05r01.nc4"
stats_filename: "20240701_som_floodscan_adm1.xlsx"
key: "key"

dataset_names:
  HDX-FLOODSCAN: "hdx-floodscan"

allowed_tags:
  - "climate hazards"
  - "climate-weather"
  - "hydrology"
  - "natural disasters"

# Metadata
title: "HDX FloodScan"
update_frequency: "daily"
maintainer_id: "2f9fd160-2a16-49c0-89d6-0bc3230599bf"
organization_id: "hdx"
description_90days_file: "Daily zip file containing previous 90 days of raster both SFED and SFED baseline bands."
description_stats_file: "Excel file containing date, admin metadata, raw SFED mean values (per admin 2), and equivalent approximate calculated return period."
notes: "HDX FloodScan Notes"